### ISSUE TITLE
Displaying stats for multiple repositories

### ISSUE THREAD

**Issue by sbmthakur** [ashutosh1919/report-curator#3]
At present, we are only displaying stats for the repository in context. I believe displaying stats for all repositories of the user will make more sense. We can get the list of repositories for the user with [List repositories for the authenticated user](https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user). 

Certain users can have many repositories. In such cases, we can only use metrics from the repositories that were updated in the last year.

**Comment by ashutosh1919** [comment]
@sbmthakur the repository is a github action and it will be included in a repository. So, displaying all repository stats doesn't make any sense. Let me know if I am missing something.

**Comment by sbmthakur** [comment]
I was thinking of a different use-case where users apply this action on a repository and use that to generate stats for all of their repositories. For example, I have a GitHub repository called `report-curator` and with this action applied on it, I will have a summary of all repositories at http://sbmthakur.github.io/report-curator. I do realize that it will be difficult to automate this process without a cron-job.

We can ignore this use case as that is not the intended purpose of this action. 

As an aside, I was wondering how the generated report will be accessed when the action is applied to individual repositories? As of now, the static assets go under a branch that can be defined in the workflow(default: report). The _user_ can access the report at _http://user.github.io/my-repo_. However, this may not work if the _user_  has already pointed GitHub pages to some other branch.

**Comment by ashutosh1919** [comment]
Yes. For that, we still need to provide flexibility to deploy to netlify. That part is not implemented yet
